// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYl2q3G6Ry8WDw6WooOc9pN2mMCa7OX1w',
    appId: '1:500389562716:web:2dba3d4e9d39faff319999',
    messagingSenderId: '500389562716',
    projectId: 'my-notes-ce1a6',
    authDomain: 'my-notes-ce1a6.firebaseapp.com',
    storageBucket: 'my-notes-ce1a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABjys3tURCOsgxvW17Dpzx3yBArqqz2SI',
    appId: '1:500389562716:android:62942f383a67f578319999',
    messagingSenderId: '500389562716',
    projectId: 'my-notes-ce1a6',
    storageBucket: 'my-notes-ce1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEshL6bAT0LhIuJ5CbTewRO5AFKsfGt3Y',
    appId: '1:500389562716:ios:1db1cd0cb36f223e319999',
    messagingSenderId: '500389562716',
    projectId: 'my-notes-ce1a6',
    storageBucket: 'my-notes-ce1a6.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEshL6bAT0LhIuJ5CbTewRO5AFKsfGt3Y',
    appId: '1:500389562716:ios:1db1cd0cb36f223e319999',
    messagingSenderId: '500389562716',
    projectId: 'my-notes-ce1a6',
    storageBucket: 'my-notes-ce1a6.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYl2q3G6Ry8WDw6WooOc9pN2mMCa7OX1w',
    appId: '1:500389562716:web:a97f227cf4fce191319999',
    messagingSenderId: '500389562716',
    projectId: 'my-notes-ce1a6',
    authDomain: 'my-notes-ce1a6.firebaseapp.com',
    storageBucket: 'my-notes-ce1a6.firebasestorage.app',
  );
}
